In [4]:
import numpy as np

a= np.array([1,2,3])
k= np.array([1,2,3], dtype=np.int32)
print(a)

b = np.array([[9.0, 8.0, 7.0], [6.0, 7.0, 8.0]])
print("\n", b)

c = a * b
print("\n", c)

#diamensions
a.ndim # number dimensions = 1d array

#shape
a.shape # print out 3 

b.shape # print out (2,3) 2 rows and 3 columns

#get Type nd Size
a.dtype # print out int32
b.dtype # print out float64
a.size # print out 3 as there are 3 elements in the array
b.size # print out 6 as there are 6 elements in the array
a.itemsize # print out 4 as each element takes 4 bytes
b.itemsize # print out 8 as each element takes 8 bytes
a.nbytes # print out 12 as the total bytes taken by the array (3 elements * 4 bytes each)
b.nbytes # print out 48 as the total bytes taken by the array (6 elements * 8 bytes each)

k.itemsize# print out 4 as each element in array k takes 4 bytes (int32)



# Two transformations
A = np.array([[2, 1], [0, 3]])      # a shear + scale
B = np.array([[0, -1], [1, 0]])     # 90° counterclockwise rotation

# Apply B first, then A  (this is what A @ B means — right to left!)
AB = A @ B
BA = B @ A

print("A @ B (B first, then A):")
print(AB)
print()
print("B @ A (A first, then B):")
print(BA)
print()
print("Are they equal?", np.array_equal(AB, BA))




[1 2 3]

 [[9. 8. 7.]
 [6. 7. 8.]]

 [[ 9. 16. 21.]
 [ 6. 14. 24.]]
A @ B (B first, then A):
[[ 1 -2]
 [ 3  0]]

B @ A (A first, then B):
[[ 0 -3]
 [ 2  1]]

Are they equal? False
