In [ ]:
import numpy as np

a= np.array([1,2,3])
k= np.array([1,2,3], dtype=np.int32)
print(a)

b = np.array([[9.0, 8.0, 7.0], [6.0, 7.0, 8.0]])
print("\n", b)

c = a * b
print("\n", c)

#diamensions
a.ndim # number dimensions = 1d array

#shape
a.shape # print out 3 

b.shape # print out (2,3) 2 rows and 3 columns

#get Type nd Size
a.dtype # print out int32
b.dtype # print out float64
a.size # print out 3 as there are 3 elements in the array
b.size # print out 6 as there are 6 elements in the array
a.itemsize # print out 4 as each element takes 4 bytes
b.itemsize # print out 8 as each element takes 8 bytes
a.nbytes # print out 12 as the total bytes taken by the array (3 elements * 4 bytes each)
b.nbytes # print out 48 as the total bytes taken by the array (6 elements * 8 bytes each)

k.itemsize# print out 4 as each element in array k takes 4 bytes (int32)



# Two transformations
A = np.array([[2, 1], [0, 3]])      # a shear + scale
B = np.array([[0, -1], [1, 0]])     # 90° counterclockwise rotation

# Apply B first, then A  (this is what A @ B means — right to left!)
AB = A @ B
BA = B @ A

print("A @ B (B first, then A):")
print(AB)
print()
print("B @ A (A first, then B):")
print(BA)
print()
print("Are they equal?", np.array_equal(AB, BA))


a = np.array([[7,8,9,0,1,2,3], [1,2,3,4,5,6,7]])
print(a[0, 1]) # print out 8
print(a[0,:])   # print out [7 8 9 0 1 2 3] all the elements in the first row
print(a[:,0])   # print out [7 1] all the elements in the first column


a[1,4] = 5
print(a)

a[1, :] = 1
print(a)


# Initialize array
np.zeros((2,3), dtype=np.float64) # print out [[0. 0. 0.] [0. 0. 0.]] a 2x3 array of zeros
np.ones((2,3), dtype=np.int16)  # print out [[1. 1. 1.] [1. 1. 1.]] a 2x3 array of ones 
np.full((2,3), 7) # print out [[7 7 7] [7 7 7]] a 2x3 array filled with the value 7
np.full_like(a, 4) # print out [[4 4 4 4 4 4 4] [4 4 4 4 4 4 4]] a new array with the same shape as a, filled with the value 4
np.random.rand(2,3) # print out a 2x3 array of random floats between 0 and 1
np.random.randint(0,10,(2,3)) # print out a 2x3 array of random integers between 0 and 9







[1 2 3]

 [[9. 8. 7.]
 [6. 7. 8.]]

 [[ 9. 16. 21.]
 [ 6. 14. 24.]]
A @ B (B first, then A):
[[ 1 -2]
 [ 3  0]]

B @ A (A first, then B):
[[ 0 -3]
 [ 2  1]]

Are they equal? False
8
[7 8 9 0 1 2 3]
[7 1]
[[7 8 9 0 1 2 3]
 [1 2 3 4 5 6 7]]
[[7 8 9 0 1 2 3]
 [1 1 1 1 1 1 1]]


array([[4, 3, 6],
       [8, 0, 8]])

In [6]:
np.identity(3) # print out [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]] a 3x3 identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.ones((5,5))
arr[1:4, 1:4] = 0
arr[2,2] =9 
print(arr)

In [21]:
a = np.array([1,2,3])
b = a # b is a reference to the same array as a, not a copy
b[0] = 100

print(b, a)

c= a.copy() # c is a copy of a, not a reference
c[0] = 200  
print(c, a)

[100   2   3] [100   2   3]
[200   2   3] [100   2   3]
